/**
 * Hand-curated companion types for response bodies that the live Swagger
 * document does not describe. types.generated.ts is regenerated by
 * `npm run gen:types` and overwrites itself — keep these here so they
 * survive regeneration.
 *
 * Source of truth for these shapes: JellyBaseballV2/docs/web-client/AUTH.md
 * and the contracts/auth.md document in this branch.
 */

import type { components } from './types.generated';

export type RegisterRequest = components['schemas']['RegisterRequest'];
export type LoginRequest = components['schemas']['LoginRequest'];
export type RefreshRequest = components['schemas']['RefreshRequest'];

export interface AuthResponse {
  accessToken: string;
  refreshToken: string;
  expiresIn: number;
}

export interface UserProfileDto {
  id: string;
  email: string;
  firstName?: string | null;
  lastName?: string | null;
  avatarUrl?: string | null;
}
