/**
 * Hand-curated companion types for response bodies that the live Swagger
 * document does not describe. types.generated.ts is regenerated by
 * `npm run gen:types` and overwrites itself — keep these here so they
 * survive regeneration.
 *
 * Source of truth for these shapes: JellyBaseballV2/docs/web-client/AUTH.md
 * and the contracts/auth.md document in this branch.
 */

import type { components } from './types.generated';

export type RegisterRequest = components['schemas']['RegisterRequest'];
export type LoginRequest = components['schemas']['LoginRequest'];
export type RefreshRequest = components['schemas']['RefreshRequest'];

export interface AuthResponse {
  accessToken: string;
  refreshToken: string;
  expiresIn: number;
}

export interface UserProfileDto {
  id: string;
  email: string;
  firstName?: string | null;
  lastName?: string | null;
  avatarUrl?: string | null;
}

// ── Player domain ─────────────────────────────────────────────────────────────

export interface TeamSummaryDto {
  mlbTeamId: number;
  name: string;
  abbreviation: string;
}

export interface PositionDto {
  positionId: number;
  name: string;
  abbreviation: string;
}

export interface PlayerSummaryDto {
  mlbPlayerId: number;
  fullName: string;
  primaryPosition: string;
  mlbTeam?: TeamSummaryDto | null;
  status: string;
  jellyScore?: number | null;
}

export interface PlayerProfileDto {
  mlbPlayerId: number;
  fullName: string;
  primaryPosition: string;
  mlbTeam?: TeamSummaryDto | null;
  status: string;
  birthDate?: string | null;
  height?: string | null;
  weight?: number | null;
  news: unknown[];
}

export interface PagedResult<T> {
  items: T[];
  totalCount: number;
  pageNumber: number;
  pageSize: number;
  totalPages: number;
  hasNextPage: boolean;
  hasPreviousPage: boolean;
}

export interface PlayerSearchParams {
  nameQuery?: string;
  positionId?: number;
  mlbTeamId?: number;
  statusCode?: string;
  availability?: 'All' | 'FreeAgent' | 'Owned';
  leagueId?: number;
  pageNumber?: number;
  pageSize?: number;
  sortBy?: string;
  sortOrder?: 'asc' | 'desc';
}

export interface ScoreCategoryDto {
  name: string;
  statValue: number;
  weight: number;
  points: number;
}

export interface ScoreBreakdownDto {
  mlbPlayerId: number;
  scoringConfigId: string;
  totalScore: number;
  categories: ScoreCategoryDto[];
}

// ── Scoring configs ───────────────────────────────────────────────────────────

export interface ScoringConfigDto {
  id: string;
  name: string;
  categoriesJson: string;
  createdAt: string;
}

export interface CreateScoringConfigRequest {
  name: string;
  categoriesJson: string;
}

// ── Saved searches ────────────────────────────────────────────────────────────

export interface SavedSearchDto {
  id: string;
  name: string;
  filtersJson: string;
  createdAt: string;
}

export interface CreateSavedSearchRequest {
  name: string;
  filtersJson: string;
}

// ── Leagues ───────────────────────────────────────────────────────────────────

export interface LeagueSummaryDto {
  id: number;
  name: string;
  type: string;
  status: string;
  teamName?: string | null;
}

export interface LeagueDto {
  id: number;
  name: string;
  type: string;
  status: string;
  commissionerUserId: string;
  maxTeams: number;
  currentWeek: number;
  createdAt: string;
}

export interface LeagueMemberDto {
  id: number;
  userId: string;
  teamName: string;
  status: string;
  faabBudgetRemaining: number;
}

export interface CreateLeagueRequest {
  name: string;
  type: string;
  maxTeams: number;
}

export interface JoinLeagueRequest {
  token: string;
  teamName: string;
}

export interface LeagueInvitePreviewDto {
  leagueId: number;
  leagueName: string;
  inviterTeamName: string;
  expiresAt: string | null;
}

export interface LeagueInviteCodeDto {
  inviteCode: string;
}

export interface RosterSettingsDto {
  maxPlayers: number;
  maxBenchPlayers: number;
  positionSlotsJson: string;
}

export interface ScoringSettingsDto {
  statCategoriesJson: string;
}

export interface DraftSettingsDto {
  draftType: string;
  draftStatus: string;
  scheduledAt: string | null;
  secondsPerPick: number;
  draftOrderJson: string;
}

// ── Teams / Lineups ───────────────────────────────────────────────────────────

export interface TeamDashboardDto {
  leagueId: number;
  teamName: string;
  currentWeek: number;
  faabBudgetRemaining: number;
  rosterSize: number;
}

export interface RosterSpotDto {
  id: number;
  mlbPlayerId: number;
  playerName: string;
  primaryPosition: string;
  status: 'Active' | 'Bench' | 'InjuredReserve';
  mlbTeamAbbreviation?: string | null;
}

export interface TeamLineupSlotDto {
  slotPosition: string;
  mlbPlayerId: number | null;
  playerName: string | null;
  isLocked: boolean;
}

export interface TeamLineupDto {
  leagueId: number;
  week: number;
  slots: TeamLineupSlotDto[];
}

export interface SetLineupSlotRequest {
  week: number;
  slotPosition: string;
  mlbPlayerId: number;
}

export interface MoveRosterSpotRequest {
  rosterSpotId: number;
  newStatus: 'Active' | 'Bench' | 'InjuredReserve';
}

export interface AddFreeAgentRequest {
  addPlayerId: number;
  dropRosterSpotId?: number;
}
